### ISSUE TITLE
Duplicate color on line 46

### ISSUE THREAD

**Issue by Jeff-Haas** [mic159/sparkfun_button_2x2#2]
Color value on line 46 duplicates color value on previous line.

Color color_states[] = {
  Color(0  , 0  , 0  ),
  Color(255, 0  , 0  ),
  Color(0  , 255, 0  ),
  Color(0  , 0  , 255),
  Color(255, 255, 0  ),
  Color(0  , 255, 255),
  Color(0  , 255, 255),    // Duplicate of previous line

Suggest changing it to:
Color(255  , 0   , 255),

And thanks for this library!  It makes setting this board up much easier!

**Comment by mic159** [comment]
Woha, thanks for taking the time to raise an issue!
Fixed in https://github.com/mic159/sparkfun_button_2x2/commit/ea61a3c9339fc9de97e6e7ac122ec94ce81e49a3
